//===- KeaDialect.h - KEA dialect declaration -------------------*- C++ -*-===//
#ifndef KEA_DIALECT_KEADIALECT_H
#define KEA_DIALECT_KEADIALECT_H

#include "mlir/IR/Dialect.h"

// Generated by `-gen-dialect-decls`; note the "KeaOps" prefix, which comes from
// the first argument of add_mlir_dialect().
#include "kea/Dialect/KeaOpsDialect.h.inc"

#endif // KEA_DIALECT_KEADIALECT_H
